CreateEnBlogsNgrams <- function(n=numeric()){
    enBlogs <- stri_read_lines("~/datasciencecoursera/Courses/Capstone/Coursera-SwiftKey/final/en_US/en_US.blogs.txt") #user 3.437, system .496, elapsed 3.982
    set.seed(100)
    enBlogsSubset <- sample(enBlogs, size=length(enBlogs)*n, replace=FALSE)
    
    enBlogsUnigrams <- dfm(enBlogsSubset, ngrams = 1)
    enBlogsBigrams <- dfm(enBlogsSubset, ngrams = 2)
    enBlogsTrigrams <- dfm(enBlogsSubset, ngrams=3)
    enBlogsQuadgrams <- dfm(enBlogsSubset, ngrams=4)
    enBlogsPentagrams <- dfm(enBlogsSubset, ngrams=5)
    enBlogsHexagrams <- dfm(enBlogsSubset, ngrams=6)
    
    save(enBlogsUnigrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsUnigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsUnigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
    save(enBlogsBigrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsBigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsBigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
    save(enBlogsTrigrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsTrigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsTriigrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
    save(enBlogsQuadgrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsQuadgrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsQuadgrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
    save(enBlogsPentagrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsPentagrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsPentagrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
    save(enBlogsHexagrams, file="~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsHexagrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/enBlogsHexagrams.RData")
    unlink("~/datasciencecoursera/Courses/Capstone/capstoneproject/.RData")
}